let pokeElements = {
    normal: files/image/normal,
    flying: files/image/fly,
    fire: files/image/fogo,
    water: files/image/water,
    bug: files/image/bug,
    dragon: files/image/dragao,
    electric: files/image/eletric,
    fairy: files/image/fada,
    steel: files/image/metal,
    psychic: files/image/psychic,
    fighting: files/image/fighting,
    poison: files/image/poison,
    rock: files/image/rock,
    ground: files/image/terra,
    ghost: files/image/fantasma,
    dark: files/image/dark,
    ice: files/image/ice,
    grass: files/image/planta,
}